name: "Terraform Init"

on:
  push:
    branches:
      - development

jobs:
  init:
    name: "Terraform Init"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.6.5

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: "terraform"
          iac_version: "v14"
          policy_type: "azure"
          only_warn: true
          sarif_upload: true
          non_recursive: false
          iac_dir:
          policy_path:
          skip_rules:
          config_path:

      - name: Login to Azure
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config="backend.tfvars"
        working-directory: ./terraform/development

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform/development
